version: '3.8'

volumes:
  insignia_db:
  dragonflydb:

services:
  insignia_db:
    build:
      context: ../docker
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: insignia
      POSTGRES_PASSWORD: supersecurepw
      POSTGRES_DATABASE: insignia
    volumes:
      - insignia_db:/var/lib/postgresql/data
    healthcheck:
      test: [CMD-SHELL, pg_isready]
      interval: 8s
      timeout: 8s
      retries: 8

  mock_1st_partner_integration:
    image: kennethreitz/httpbin
    ports:
      - 8082:80
    environment:
      GUNICORN_CMD_ARGS: --capture-output --error-logfile - --access-logfile -

  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.10.0
    ports:
      - 6379:6379
    volumes:
      - dragonflydb:/data
