---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: insignia-dragonfly
  namespace: default
spec:
  replicas: 1
  resources:
    requests:
      cpu: 64m
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 512Mi
