---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: insignia-pg
  namespace: default
spec:
  instances: 1

  storage:
    size: 1Gi

  walStorage:
    size: 1Gi

  bootstrap:
    initdb:
      owner: insignia
      database: insignia

  managed:
    roles:
    - name: insignia
      ensure: present
      login: true
      superuser: true

  postgresql:
    extensions:
    - name: http
      ld_library_path:
        - system
      image:
        reference: ghcr.io/xshadowlegendx/insignia:cnpg-http-ext-pg18
