---
apiVersion: v1
kind: Secret
metadata:
  name: insignia
  namespace: default
type: Opaque
data:
  sessionKey: bLKwzepfnxe8bsGMD1jCvv0SK0gzv6nMDkGBxkIHkWYJOHJPiM5IR4ZPEg6yucq66k/PZQRQFlFvE4YhJgMEAA==
  jwtPublicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQUVEcTlnZ3AzL042MnRvZVN4Rm5LTnNsUGExWjQwbHRmclBNTEdtYWN0bFE9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
  jwtPrivateKey: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1DNENBUUF3QlFZREsyVndCQ0lFSUM1djFCY1VuaGl0SmtpWEhMdDdMUmN3QjMrcFFnSXI4Y3JTWFkrWGRJNXoKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
