//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "delegable_user_permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub label: Option<String>,
    pub zanzibar_value: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::oauth_scopes::Entity")]
    OauthScopes,
}

impl Related<super::oauth_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthScopes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
