//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "oauth_clients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub label: Option<String>,
    pub client_id: String,
    pub client_secret: Option<String>,
    pub authn_flow: Option<String>,
    pub client_type: String,
    pub audiences: Vec<String>,
    pub redirect_uris: Vec<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_oauth_consents::Entity")]
    UsersOauthConsents,
}

impl Related<super::users_oauth_consents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersOauthConsents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
