//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "oauth_scopes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub label: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub delegable_user_permission_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::delegable_user_permissions::Entity",
        from = "Column::DelegableUserPermissionId",
        to = "super::delegable_user_permissions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DelegableUserPermissions,
    #[sea_orm(has_many = "super::users_oauth_consents::Entity")]
    UsersOauthConsents,
}

impl Related<super::delegable_user_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DelegableUserPermissions.def()
    }
}

impl Related<super::users_oauth_consents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersOauthConsents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
