//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users_oauth_consents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub oauth_scope_id: i32,
    pub oauth_client_id: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::oauth_clients::Entity",
        from = "Column::OauthClientId",
        to = "super::oauth_clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OauthClients,
    #[sea_orm(
        belongs_to = "super::oauth_scopes::Entity",
        from = "Column::OauthScopeId",
        to = "super::oauth_scopes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OauthScopes,
}

impl Related<super::oauth_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthClients.def()
    }
}

impl Related<super::oauth_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthScopes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
