//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users_oauth_authorized_clients")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub token_key: String,
    pub user_id: Uuid,
    pub oauth_client_id: i32,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::oauth_clients::Entity",
        from = "Column::OauthClientId",
        to = "super::oauth_clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    OauthClients,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::users_oauth_consents::Entity")]
    UsersOauthConsents,
}

impl Related<super::oauth_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthClients.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::users_oauth_consents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersOauthConsents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
