//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub session_data: String,
    pub recovery_data: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub password: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub phone: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    pub phone_verified_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub twofa_enabled_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_oauth_authorized_clients::Entity")]
    UsersOauthAuthorizedClients,
    #[sea_orm(has_many = "super::users_webauthn_credentials::Entity")]
    UsersWebauthnCredentials,
}

impl Related<super::users_oauth_authorized_clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersOauthAuthorizedClients.def()
    }
}

impl Related<super::users_webauthn_credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersWebauthnCredentials.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
