//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "well_known_configs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ios_app_ids: Vec<String>,
    pub android_package_name: Option<String>,
    pub android_sha256_fingerprints: Vec<String>,
    pub openid_issuer_url: Option<String>,
    pub openid_authorize_url: Option<String>,
    pub openid_jwk_url: Option<String>,
    pub openid_token_endpoint: Option<String>,
    pub openid_user_info_endpoint: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
