
syntax = "proto3";

package dev.insigniaoss.service.v0;

import "insigniaoss/type/user.proto";

message ValidateUserContextReq {
  string access_token = 1;
  map<string, string> req_headers = 2;
}

message GetUserInfoReq {
  string user_id = 1;
}

message UserContext {
  bool is_session_valid = 1;
  optional dev.insigniaoss.type.User user = 2;
}

service IntegrationService {
  rpc GetUserInfo (GetUserInfoReq) returns (dev.insigniaoss.type.User);

  rpc ValidateUserContext (ValidateUserContextReq) returns (UserContext);
}
